version: "2"
checks:
  method-complexity:
    config:
      threshold: 8
  file-lines:
    config:
      threshold: 500
engines:
  bandit:
    enabled: true
    checks:
      assert_used:
        enabled: false
