site_name: ormar
site_description: An simple async ORM with fastapi in mind and pydantic validation.
nav:
  - Overview: index.md
  - Installation: install.md
  - Models: models.md
  - Fields: fields.md
  - Relations: relations.md
  - Queries: queries.md
  - Use with Fastapi: fastapi.md
  - Contributing: contributing.md
repo_name: collerek/ormar
repo_url: https://github.com/collerek/ormar
google_analytics:
  - UA-72514911-3
  - auto
theme:
  name: material
  highlightjs: true
  hljs_languages:
      - python
  palette:
    primary: indigo
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.snippets:
      base_path: docs
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      linenums: true
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/highlight.min.js
  - javascripts/config.js
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/styles/default.min.css