site_name: ormar
site_description: A simple async ORM with fastapi in mind and pydantic validation.
nav:
  - Overview: index.md
  - Installation: install.md
  - Models:
    - Definition: models/index.md
    - Methods: models/methods.md
    - Migrations: models/migrations.md
    - Internals: models/internals.md
  - Fields:
    - Fields types: fields/field-types.md
    - Common parameters: fields/common-parameters.md
  - Relations:
    - relations/index.md
    - relations/foreign-key.md
    - relations/many-to-many.md
    - relations/queryset-proxy.md
  - Queries: queries.md
  - Signals: signals.md
  - Use with Fastapi: fastapi.md
  - Use with mypy: mypy.md
  - PyCharm plugin: plugin.md
  - Contributing: contributing.md
  - Release Notes: releases.md
repo_name: collerek/ormar
repo_url: https://github.com/collerek/ormar
#google_analytics:
#  - UA-72514911-3
#  - auto
theme:
  name: material
  highlightjs: true
  hljs_languages:
      - python
  palette:
    primary: indigo
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.snippets:
      base_path: docs
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      linenums: true
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/highlight.min.js
  - javascripts/config.js
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/styles/default.min.css