name: Build Documentation using MkDocs
on:
  push:
    branches: [ master ]
jobs:
  build:
    name: Build and Deploy Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master
        uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material pydoc-markdown
          pydoc-markdown --build --site-dir=api
      - name: Copy APi docs
        run: cp -Tavr ./build/docs/content/ ./docs/api/
      - name: Deploy
        run: |
          mkdocs gh-deploy --force
